# Generated by Django 3.2.25 on 2024-03-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('avatar', models.CharField(blank=True, default='', max_length=300)),
                ('cover_image', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
